#!/bin/bash

WORKDIR=$PWD
ENV="PATH=/home/node/node_modules/.bin:$PATH"

PODMAN_ARGS=(
	--rm
	--security-opt label=disable
	--userns keep-id
	--volume $PWD:$PWD
	--workdir "${WORKDIR}"
	-it
	--init
)

POST_ARGS=()

if [[ x"$1" = x"ng" ]]; then
	PODMAN_ARGS+=( -e "${ENV}" )
	PODMAN_ARGS+=( --volume $PWD/node_modules:/home/node/node_modules )
	if [[ x"$2" = x"serve" ]]; then
		PODMAN_ARGS+=( -p "4200:4200" )
		POST_ARGS+=( --host "0.0.0.0" )
		POST_ARGS+=( --disable-host-check )
	fi
elif [[ x"$1" = x"json-server" ]]; then
	PODMAN_ARGS+=( -e "${ENV}" )
	PODMAN_ARGS+=( --volume $PWD/node_modules:/home/node/node_modules )
	PODMAN_ARGS+=( -p "[::1]:3000:3000" )
fi

podman run "${PODMAN_ARGS[@]}" node:alpine $@ "${POST_ARGS[@]}"