#!/bin/bash

ROOT=$(dirname $(realpath $0))
PROJECT=$(basename $ROOT)
IMAGE=${IMAGE:-localhost/angular:alpine}

PODMAN_ARGS=(
	--rm
	--security-opt label=disable
	--userns keep-id
	--volume "${ROOT}:/home/node/${PROJECT}"
	--workdir "/home/node/${PROJECT}"
	--init
	-it
)

POST_ARGS=()

if [[ x"$1" = x"ng" ]] then
	if [[ x"$2" = x"serve" ]]; then
		PODMAN_ARGS+=( -p "4200:4200" )
		POST_ARGS+=( --host "0.0.0.0" )
		POST_ARGS+=( --disable-host-check )
	elif [[ x"$2" = x"test" ]]; then
		PODMAN_ARGS+=( -p "9876:9876" )
		PODMAN_ARGS+=( --env 'CHROME_BIN=/usr/bin/chromium-browser')
	fi
fi

podman run "${PODMAN_ARGS[@]}" "${IMAGE}" $@ "${POST_ARGS[@]}"